shnc/urls.py
# shnc/urls
from django.conf.urls import url
from shnc import views,views_hr,views_bills

#template tagging
app_name = 'shnc'
urlpatterns = [
    url(r'^user_login/$',views.user_login ,name='user_login'),
    url(r'^welcome/$',views.welcome ,name='welcome'),
    url(r'^admin/$',views.AdminListView.as_view(),name='admin_list'),
    url(r'^admin//(?P<pk>\d+)/$',views.AdminDetailView.as_view(),name='admin_details'),
    
#####################################################################################    
    url(r'^bills/$',views_bills.BillListView.as_view(),name='bill_list'),
    url(r'^bills/(?P<pk>\d+)/$',views_bills.BillDetailView.as_view(),name='bill_details'),
    url(r'^bills/new/$',views_bills.CreateBillView.as_view() ,name='bill_new'),

    
    # url(r'^hr/add_nurse/$',views.add_nurse ,name='add_nurse'),
#####################################################################################
    url(r'^hr/view_nurses/$',views_hr.LpnListView.as_view() ,name='lpn_list'),
    url(r'^hr/(?P<pk>\d+)/$',views_hr.LpnDetailView.as_view() ,name='lpn_details'),
    url(r'^hr/new/$',views_hr.CreateLpnView.as_view() ,name='lpn_new'),
    url(r'^hr/(?P<pk>\d+)/edit/$',views_hr.LpnUpdateView.as_view() ,name='lpn_update'),
    url(r'^hr/(?P<pk>\d+)/remove/$',views_hr.LpnDeleteView.as_view() ,name='lpn_remove'),
#####################################################################################
    url(r'^admin/add_user/$',views.add_user ,name='add_user'),
     
]

shnc/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse

###########################################
        
class UserProfileInfo(models.Model):
    
    user = models.OneToOneField(User)
    privileges = models.CharField(max_length=80)
    phone_number = models.CharField(max_length=80)
    
    def __str__(self):
        return self.user.username
        
###########################################       
class AccessRecord(models.Model):
    # name = models.ForeignKey(Webpage)
    date = models.DateField()
    # time = models.TimeField()
    user = models.CharField(max_length=80)
    form = models.CharField(max_length=80)
    action = models.CharField(max_length=80)
    
    def __str__(self):
        return self.date
        
###########################################        
class LpnData(models.Model):
    
    first_name = models.CharField(max_length=80)
    middle_name = models.CharField(max_length=80)
    last_name = models.CharField(max_length=80)
    email = models.EmailField(unique=True)
    phone_number = models.CharField(max_length=80,unique=True)
    # text = forms.CharField(widget=forms.Textarea)
    license_id = models.CharField(max_length=80,unique=True)
    license_exp = models.DateField()
    cpr_exp = models.DateField()
    cpr_provider = models.CharField(max_length=80)
    
    def publish(self):
        self.save()
        
    def get_absolute_url(self):
        return reverse('shnc:hr') 
        
class Bills(models.Model):
    agency = models.CharField(max_length=80)
    provider = models.CharField(max_length=80)
    location = models.CharField(max_length=80)
    date_due = models.DateField()
    amount = models.CharField(max_length=80)
    overdue = models.BooleanField(default=False)
    paid = models.BooleanField(default=False)
    
    def paid_publish(self):
        self.paid = True
        self.save()
        
    def get_absolute_url(self):
        return reverse("shnc:bills_list") 
        
    def __str__(self):
        return self.provider
# Create your models here.

shnc/forms.py
from django import forms
from django.core import validators
from shnc.models import LpnData, UserProfileInfo,Bills
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse

# create custom validators

def check_for_z(value):
    if value[0].lower() != 'z':
        raise forms.ValidationError("Does not start with z")
###########################################

class UserForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'New Username','autocomplete':'off'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'New Password', 'autocomplete': 'new-password'}) )
    email = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'example: abc@gmail.com','autocomplete':'off'}))
    class Meta:
        model = User
        fields = ('username','email','password')
        
class user_profile_form(forms.ModelForm):
    phone_number = forms.CharField(label='Phone Number',required=False)
    
    class Meta:
        model = UserProfileInfo
        fields = ('privileges','phone_number')

###########################################
#forms
class add_nurse_form(forms.ModelForm):
    first_name = forms.CharField(label='First Name')
    middle_name = forms.CharField(label='Middle Name' ,required=False)
    last_name = forms.CharField(label='Last Name')
    email = forms.EmailField(required=False)
    phone_number = forms.CharField(label='Phone Number',required=False)
    # text = forms.CharField(widget=forms.Textarea)
    license_id = forms.CharField(label='License ID') 
    license_exp = forms.DateField(label='License Expiration',widget=forms.TextInput(attrs={'placeholder': 'Format:   01/01/2018'}))
    cpr_exp = forms.DateField(label='CPR Expiration' )
    cpr_provider = forms.CharField(label='CPR Provider' )
    botcatcher = forms.CharField(required=False, widget=forms.HiddenInput, validators=[validators.MaxLengthValidator(0)])
    
    class Meta:
        model = LpnData
        fields = '__all__'
        
###########################################

class BillForm(forms.ModelForm):
    
    class Meta:
        model = Bills
        fields = '__all__'
 

shnc/views.py
from django.shortcuts import render
from shnc.forms import user_profile_form,UserForm
# from django.urls import reverse_lazy
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (TemplateView,UpdateView, DeleteView, ListView, DetailView, CreateView)
from django.contrib.auth.models import User


###########################################
###########################################

def index(request):
    my_dict = {'insert_me':"hello dsfsfsd views"}
    context_dict = {'text':"hello world", 'number':34}
    return render(request,'shnc/login.html', context=context_dict)

###########################################
@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))
    
###########################################  

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        
        user = authenticate(username=username,password=password)
        
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('shnc:welcome'))
            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
        else:
            print("not correct login")
            return HttpResponseRedirect(reverse('shnc:user_login'))
    else:
        return render(request,'shnc/login.html')

###########################################    
@login_required    
def welcome(request):
    return render(request,'shnc/welcome.html')
    

###########################################    



class AdminListView(LoginRequiredMixin,ListView):
    login_url = '/shnc/user_login/'
    model = User
    context_object_name = 'users'
    template_name = 'shnc/admin/admin_list.html'
    # def get_queryset(self):
    #     return LpnData.objects.all()
    
class AdminDetailView(LoginRequiredMixin,DetailView):
    login_url = '/shnc/user_login/'
    model = User        
    context_object_name = 'user'
    template_name = 'shnc/admin/admin_details.html'


    
###########################################    

@login_required        
def add_user(request):
    if request.method=='POST':
        profile_form=user_profile_form(request.POST) 
        user_form = UserForm(request.POST)
        if profile_form.is_valid() and user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            
            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()
            return HttpResponseRedirect(reverse('shnc:admin'))
        else:
            print("error form invald")
        #save data to db 
    else:
        profile_form=user_profile_form() 
        user_form = UserForm()
        return render(request,'shnc/admin/add_user.html',{'profile_form':profile_form, 'user_form':user_form})

templates/shnc/base.html
<!DOCTYPE html
{% load staticfiles %}
<html>
<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
<link href="https://fonts.googleapis.com/css?family=Spectral+SC" rel="stylesheet">
<link rel="stylesheet" href="{% static 'css/app.css' %}">
<meta name="viewport" content="initial-scale=1, maximum-scale=1">

<head>
	<title>SHNC</title>
<body>


    <div class="container">
  <div id="logo">
  
        <img src="{% static 'images/res_logo.png' %} "></img>

  </div>
 {% if user.is_authenticated %}
   <div id="logout_top" >
      <a class="btn btn-dark" href="{% url 'user_logout' %}">
          <span class="glyphicon glyphicon-log-out"></span> Log out
      </a>
  </div>
 {% else %}
   <li id="logout_top" >
     <a class="navbar-link" href="{% url 'shnc:user_login' %}">Login</a>

   </li>
 {% endif %}
  <nav class="navbar navbar-default">

      <div class="navbar-header">
         <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-nav-demo" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span> 
        </button>
      </div>
      <div class="collapse navbar-collapse" id="bs-nav-demo">
        <ul class="nav navbar-nav">
          <li><a href="{% url 'shnc:welcome' %}">HOME</a></li>
          <li><a href="{% url 'shnc:lpn_list' %}">HR</a></li>
          <li><a href="{% url 'shnc:admin_list' %}">ADMIN</a></li>
          <li><a href="{% url 'shnc:bill_list' %}">BILLS</a></li> 
          <li><a href="">FORMS</a></li>
          <li><a href="">SUPPLIES</a></li>
          <li><a href="">CONTACTS</a></li>
        </ul>
      </div>
    
  </nav>
  </div>
  
  <div class="container">
      
    {% block body_block%}    
    {% endblock %}
  </div>
  


<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  <footer>
   Copyright 2017 by <a href="http://scarlethaven.com/">Scarlet Haven Nursing Care</a>.
  </footer>
</body>
</html>      

templates/shnc/help.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>SHNC</title>
    <!--<link rel="stylesheet" href="style.css">-->
  </head>
  <body>
    <!-- page content -->
    <h1> help </h1>
    {{insert_me}}
  </body>
</html>

templates/shnc/login.html
<!DOCTYPE html
{% load staticfiles %}
<html>
<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
<link href="https://fonts.googleapis.com/css?family=Spectral+SC" rel="stylesheet">
<link rel="stylesheet" href="{% static 'css/login.css' %}">
<meta name="viewport" content="initial-scale=1, maximum-scale=1">

<head>
	<title>Scarlet Haven Nursing Care</title>
<body>
  
  
 <!--{% if user.is_authenticated %}-->
 <!--  <li><a class="navbar-link" href="{% url 'user_logout' %}">Logout</a></li>-->
 <!--{% else %}-->
 <!--  <li><a class="navbar-link" href="{% url 'shnc:user_login' %}">Login</a></li>-->
 <!--{% endif %}-->
 
<div class="container">
      <div id="logo">
    <img src="{% static 'images/res_logo.png' %}" alt="SHNC"  />
  </div>
  <div class="login_form">
    <h1> Log In </h1>
    <form action="{% url 'shnc:user_login' %}" method='POST'>
        {% csrf_token %}
        <div>
        <label for="username">Username</label>
        <input type="text" name="username" placeholder="Enter Username"/>
        </div>
        <div>
        <label for="password">Password</label>
        <input type="password" name="password"/>
        </div>
        <input type="submit" value="Login"/>
        
        
    </form>
    </div>
 </div>   


<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

  <footer>
   Copyright 2018 by <a href="http://scarlethavenres.com/">Scarlet Haven</a>.
  </footer>
</body>
</html>

templates/shnc/logout.html
{% extends "shnc/base.html" %}
    <!-- page content -->
    {% block body_block%}
    {% load staticfiles %}
    {% load my_extras %}
    <div class="row">
        <img src="{% static 'images/shnc.png' %} "></img>
    </div>>
    <h1> Log In </h1>
    <form action="{% url 'shnc:user_login' %}" method='POST'>
        {% csrf_token %}
        <label for="username">Username</label>
        <input type="text" name="username" placeholder="Enter Username"/>
        
        <label for="password">Password</label>
        <input type="password" name="password"/>
        
        <input type="submit" value="Login"/>
        
        
    </form>
   
    {% endblock %}

templates/shnc/lpndata_list.html
<!DOCTYPE html>
{% extends "shnc/base.html" %}
    <!-- page content -->
    {% block body_block%}
    {% load staticfiles %}
     <div class="centerstage">
         {% for lpn in lpnData %}
         <div class="lpns">
             <h1><a href="{%url 'shnc:view_nurse' pk=lpnData.pk %}"> {{ lpnData.first_name}} {{ lpnData.last_name}} </a></h1>
             
         </div>>
         {% endfor %}
     </div>

    {% endblock %}

templates/shnc/other.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>SHNC</title>
    <link rel="stylesheet" href="{% static "css/mystyle.css" %}" type="text/css" />
    <!--<link rel="stylesheet" href="style.css">-->
  </head>
  <body>
    <!-- page content -->
    <h1> other </h1>
    <img src="{% static "images/shnc.png" %} " alt="not found">
    
    
  </body>
</html>

templates/shnc/welcome.html
<!DOCTYPE html>
{% extends "shnc/base.html" %}
    <!-- page content -->
    {% block body_block%}
    {% load staticfiles %}
 <div>
     <h1>Welcome</h1>
 </div>
 
 <div class="row" >
    <div class="col-md-6"  style="margin-top:20px;">  
    <div class="card ">
      <a  href="{% url 'shnc:lpn_list' %}">
          <span class="glyphicon glyphicon-flash"></span>Manage Nurses</a>
          </div>
    </div>  
    <div class="col-md-6" style="margin-top:20px;"> 
    <div class="card ">
     <a  href="{% url 'shnc:admin_list' %}">
          <span class="glyphicon glyphicon-flash"></span>Manage Admins</a>
    </div>
    </div>
    <div class="col-md-6" style="margin-top:20px;">
        <div class="card ">     
      <a href="{% url 'shnc:bill_list' %}">
          <span class="glyphicon glyphicon-flash"></span>Manage Bills</a>
   </div>
    </div>         
    <div class="col-md-6" style="margin-top:20px;">   
    <div class="card ">
      <a  href="">
          <span class="glyphicon glyphicon-flash"></span>Manage Forms</a>
   </div>
    </div>  


</div>
    {% endblock %}